project:
  type: website

website:
  title: "CONSEJO HIPOTECARIO"
  favicon: circulo_logo.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Propiedades.qmd
      
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

